name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  publish-eslint-config-pycom-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: install dependencies
        run: npm i
        working-directory: packages/eslint-config-pycom-base
      - name: publish package
        run: npm publish --access public
        working-directory: packages/eslint-config-pycom-base
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
